version: '3'

services:
  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  redis-data: